# Generated by Django 5.1.2 on 2024-10-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChineseWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplified', models.CharField(max_length=50)),
                ('traditional', models.CharField(blank=True, max_length=50)),
                ('pinyin', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('categories', models.ManyToManyField(blank=True, related_name='words', to='mindmaps.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mindmaps.chineseword')),
                ('mind_maps', models.ManyToManyField(related_name='words', to='mindmaps.mindmap')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='mind_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='mindmaps.mindmap'),
        ),
    ]
