# Generated by Django 5.1.2 on 2025-01-20 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chineseword', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordInMindMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mind_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_links', to='mindmaps.mindmap')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mindmaps.wordinmindmap')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mind_map_links', to='chineseword.chineseword')),
            ],
            options={
                'unique_together': {('word', 'mind_map')},
            },
        ),
    ]
