# Generated by Django 5.1.2 on 2024-10-10 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chineseword',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='chineseword',
            name='mind_maps',
        ),
        migrations.RemoveField(
            model_name='chineseword',
            name='parent',
        ),
        migrations.CreateModel(
            name='WordInMindMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(blank=True, related_name='words', to='mindmaps.category')),
                ('mind_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_links', to='mindmaps.mindmap')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mindmaps.wordinmindmap')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mind_map_links', to='mindmaps.chineseword')),
            ],
            options={
                'unique_together': {('word', 'mind_map')},
            },
        ),
    ]
