# Generated by Django 5.1.2 on 2024-10-10 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseword', '0001_initial'),
        ('mindmaps', '0002_remove_chineseword_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordinmindmap',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mind_map_links', to='chineseword.chineseword'),
        ),
        migrations.DeleteModel(
            name='ChineseWord',
        ),
    ]
