# Generated by Django 5.1.2 on 2024-10-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0003_alter_wordinmindmap_word_delete_chineseword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordinmindmap',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
