meta:
  environment: python
  toolchain:
    name: pip
    version: "3.11"
build:
  requirementsPath: requirements.txt
run:
  scriptName: ""
  command: >
    cd chinese_learning_platform &&
    /app/venv/bin/python3 -m gunicorn chinese_learning_platform.wsgi:application --bind 0.0.0.0:80

  persistenceMount: /data
  containerPort: "80"
services:
  web:
    build: .
    volumes:
      - ./data/static:/data/static
      - ./data/media:/data/media
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./data/static:/data/static
      - ./data/media:/data/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
