# Generated by Django 5.1.2 on 2024-10-14 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chineseword', '0008_chineseword_favorites'),
        ('users', '0010_rename_wrong_answers_m2m_deckperformance_wrong_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decks', models.ManyToManyField(blank=True, related_name='decks', to='users.deck')),
                ('words', models.ManyToManyField(blank=True, related_name='lessons', to='chineseword.chineseword')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homework_images/')),
                ('description', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LexicalExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexical_exercises', to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_file', models.FileField(blank=True, upload_to='audio/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_texts', to='lessons.lesson')),
            ],
        ),
    ]
