# Generated by Django 5.1.2 on 2025-01-20 06:03

import django.db.models.deletion
import lessons.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chineseword', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_file', models.FileField(blank=True, null=True, upload_to='lessons_files/', validators=[lessons.models.validate_pdf])),
                ('decks', models.ManyToManyField(blank=True, related_name='decks', to='users.deck')),
                ('words', models.ManyToManyField(blank=True, related_name='lessons', to='chineseword.chineseword')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homework_images/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonSupplementaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chineseword.chineseword')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='supplementary_words',
            field=models.ManyToManyField(blank=True, related_name='supplementary_lessons', through='lessons.LessonSupplementaryWord', to='chineseword.chineseword'),
        ),
        migrations.CreateModel(
            name='LessonWordsForUnderstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chineseword.chineseword')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='words_for_understanding',
            field=models.ManyToManyField(blank=True, related_name='understanding_lessons', through='lessons.LessonWordsForUnderstanding', to='chineseword.chineseword'),
        ),
        migrations.CreateModel(
            name='LexicalExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexical_exercises', to='lessons.lesson')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lessons.lexicalexercise')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_file', models.FileField(blank=True, upload_to='audio/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_texts', to='lessons.lesson')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lessonsupplementaryword',
            constraint=models.UniqueConstraint(fields=('lesson', 'chinese_word'), name='lesson_supplementarywords_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lessonwordsforunderstanding',
            constraint=models.UniqueConstraint(fields=('lesson', 'chinese_word'), name='lesson_wordsunderstanding_uniq'),
        ),
    ]
