# Generated by Django 5.1.2 on 2024-10-14 01:39

from django.db import migrations, models
from django.utils import timezone  # Import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),  # Use timezone.now as the default
        ),
    ]
