# Generated by Django 5.1.2 on 2024-10-14 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_homework_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicalexercise',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lessons.lexicalexercise'),
        ),
    ]
