# Generated by Django 5.1.2 on 2024-10-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseword', '0008_chineseword_favorites'),
        ('lessons', '0004_lexicalexercise_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='supplementary_words',
            field=models.ManyToManyField(blank=True, related_name='supplementary_lessons', to='chineseword.chineseword'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='words_for_understanding',
            field=models.ManyToManyField(blank=True, related_name='understanding_lessons', to='chineseword.chineseword'),
        ),
    ]
