# Generated by Django 5.1.2 on 2024-10-24 21:53

import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_homework_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons_files/', validators=[lessons.models.validate_pdf]),
        ),
    ]
