# Generated by Django 5.1.2 on 2024-10-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplified', models.CharField(max_length=50)),
                ('traditional', models.CharField(blank=True, max_length=50)),
                ('pinyin', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
            ],
        ),
    ]
