# Generated by Django 5.1.2 on 2025-01-20 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplified', models.CharField(max_length=50)),
                ('traditional', models.CharField(blank=True, max_length=50, null=True)),
                ('pinyin', models.CharField(blank=True, max_length=100, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('hsk_level', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChineseWordFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chineseword.chineseword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chineseword',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_words', through='chineseword.ChineseWordFavorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chinesewordfavorite',
            constraint=models.UniqueConstraint(fields=('chinese_word', 'user'), name='chineseword_favorites_uniq'),
        ),
        migrations.AddConstraint(
            model_name='chineseword',
            constraint=models.UniqueConstraint(fields=('simplified', 'pinyin', 'meaning'), name='unique_simplified_pinyin_meaning'),
        ),
    ]
