# Generated by Django 5.1.2 on 2024-10-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseword', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chineseword',
            name='meaning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chineseword',
            name='pinyin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chineseword',
            name='traditional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
