# Generated by Django 5.1.2 on 2024-10-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseword', '0002_alter_chineseword_meaning_alter_chineseword_pinyin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chineseword',
            name='pinyin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
