# Generated by Django 5.1.2 on 2024-10-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseword', '0003_alter_chineseword_pinyin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chineseword',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chineseword',
            name='simplified',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
