# Generated by Django 5.1.2 on 2024-10-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseword', '0006_alter_chineseword_hsk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chineseword',
            name='simplified',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='chineseword',
            constraint=models.UniqueConstraint(fields=('simplified', 'pinyin', 'meaning'), name='unique_simplified_pinyin_meaning'),
        ),
    ]
