# Generated by Django 5.1.2 on 2024-10-13 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseword', '0007_alter_chineseword_simplified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chineseword',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_words', to=settings.AUTH_USER_MODEL),
        ),
    ]
