# Generated by Django 5.1.2 on 2024-11-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseword', '0008_chineseword_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chineseword',
            name='hsk_level',
            field=models.CharField(blank=True, choices=[('1', 'HSK 1'), ('2', 'HSK 2'), ('3', 'HSK 3'), ('4', 'HSK 4'), ('5', 'HSK 5'), ('6', 'HSK 6')], max_length=10, null=True),
        ),
    ]
