# Generated by Django 5.1.2 on 2024-12-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='lesson',
        ),
        migrations.AddField(
            model_name='homework',
            name='lessons',
            field=models.ManyToManyField(related_name='schedule_lessons_homework', to='schedule.lesson', verbose_name='Уроки'),
        ),
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Задание'),
            preserve_default=False,
        ),
    ]
