# Generated by Django 5.1.2 on 2024-12-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_homework_lesson_homework_lessons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='lessons',
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='schedule.lesson', verbose_name='Урок'),
            preserve_default=False,
        ),
    ]
