# Generated by Django 5.1.2 on 2024-12-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_homework_lessons_homework_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время проведения'),
        ),
    ]
