# Generated by Django 5.1.2 on 2024-10-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
