# Generated by Django 5.1.2 on 2025-01-20 06:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chineseword', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeckPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_correct', models.IntegerField()),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeckPerformanceWrongAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chineseword.chineseword')),
                ('deck_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.deckperformance')),
            ],
        ),
        migrations.AddField(
            model_name='deckperformance',
            name='wrong_answers',
            field=models.ManyToManyField(blank=True, related_name='deck_performances', through='users.DeckPerformanceWrongAnswers', to='chineseword.chineseword'),
        ),
        migrations.CreateModel(
            name='DeckWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_words', to='users.deck')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_words', to='chineseword.chineseword')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='words',
            field=models.ManyToManyField(related_name='decks', through='users.DeckWord', to='chineseword.chineseword'),
        ),
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='users',
            field=models.ManyToManyField(related_name='decks', through='users.UserDeck', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WordPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef_factor', models.FloatField(default=2)),
                ('repetitions', models.IntegerField(default=0)),
                ('right', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('next_review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='chineseword.chineseword')),
            ],
        ),
        migrations.AddConstraint(
            model_name='deckperformancewronganswers',
            constraint=models.UniqueConstraint(fields=('deck_performance', 'chinese_word'), name='deckperformance_wronganswers_uniq'),
        ),
        migrations.AddIndex(
            model_name='deckword',
            index=models.Index(fields=['deck', 'word'], name='users_deckw_deck_id_792d7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deckword',
            unique_together={('deck', 'word')},
        ),
        migrations.AddIndex(
            model_name='userdeck',
            index=models.Index(fields=['user', 'deck'], name='users_userd_user_id_5598ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdeck',
            unique_together={('user', 'deck')},
        ),
        migrations.AddIndex(
            model_name='wordperformance',
            index=models.Index(fields=['user', 'word'], name='users_wordp_user_id_7d33c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wordperformance',
            unique_together={('user', 'word')},
        ),
    ]
