# Generated by Django 5.1.2 on 2024-10-12 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseword', '0007_alter_chineseword_simplified_and_more'),
        ('users', '0004_alter_deckperformance_wrong_answers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deckword',
            index=models.Index(fields=['deck', 'word'], name='users_deckw_deck_id_792d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='userdeck',
            index=models.Index(fields=['user', 'deck'], name='users_userd_user_id_5598ec_idx'),
        ),
        migrations.AddIndex(
            model_name='wordperformance',
            index=models.Index(fields=['user', 'word'], name='users_wordp_user_id_7d33c6_idx'),
        ),
    ]
