# Generated by Django 5.1.2 on 2024-10-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseword', '0007_alter_chineseword_simplified_and_more'),
        ('users', '0005_deckword_users_deckw_deck_id_792d7d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckperformance',
            name='wrong_answers_m2m',
            field=models.ManyToManyField(blank=True, related_name='deck_performances', to='chineseword.chineseword'),
        ),
    ]
