# Generated by Django 5.1.2 on 2024-10-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_deckperformance_wrong_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deckperformance',
            old_name='wrong_answers_m2m',
            new_name='wrong_answers',
        ),
    ]
